project:
  type: website

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    title: Charlotte Wickham
    right:
      - href: talks.qmd
        text: Talks
        icon: megaphone
    tools:
      - icon: github
        href: github.com
format:
  html:
    backgroundcolor: "#eeffee"
    fontcolor: "darkgreen"
    linkcolor: "black"
    mainfont: "monospace"
    fontsize: 20px
    theme: [cosmo, styles.scss]
